#!/usr/bin/env python

import sys
import re
import xml.etree.ElementTree as xml
#import lxml.etree as xml

def xml_copy(element, target):
    copy = xml.SubElement(target, element.tag, element.attrib)
    copy.text = element.text
    for child in element:
        xml_copy(child, copy)

#parser = xml.XMLParser(remove_blank_text=True)
#out = xml.parse(sys.argv[1], parser)
out = xml.parse(sys.argv[1])

fwjr = out.getroot()
pr = fwjr.find('PerformanceReport')

for f in sys.argv[2:]:
#    tree = xml.parse(f, parser)
    tree = xml.parse(f)
    for node in tree.getroot():
        if node.tag == 'PerformanceReport':
            for summary in node:
                prs = pr.find('./PerformanceSummary[@Metric="' + summary.attrib['Metric'] + '"]')
                if prs is None:
                    xml_copy(summary, pr)
                else:
                    for metric in summary:
                        prsm = prs.find('./Metric[@Name="' + metric.attrib['Name'] + '"]')
                        if prsm is None:
                            xml.SubElement(prs, metric.tag, metric.attrib)
                        else:
                            if not re.search('-(bool|string)-', prsm.attrib['Name']):
                                prsm.attrib['Value'] = str(
                                          float(prsm.attrib['Value'])
                                        + float(metric.attrib['Value'])
                                )
        else:
            xml_copy(node, fwjr)

#out.write(sys.stdout, pretty_print=True)
out.write(sys.stdout)
