import FWCore.ParameterSet.Config as cms

treemaker = cms.EDAnalyzer("TreeMaker",
							isMC = cms.bool(True),
							tauPtMin = cms.double(20),
							piPtMin = cms.double(0),
							tauEtaMax = cms.double(2.3),
							tauDzMax = cms.double(0.2),
							null = cms.double(-5),
							Triggers = cms.vstring(""),
							tauCollection = cms.string("hpsPFTauProducer"),
							muonCollection = cms.string("muons"),
							electronCollection = cms.string("gedGsfElectrons"),
							jetCollection = cms.string("ak4PFJets"),
							metCollection = cms.string("pfMet"),
							vertexCollection = cms.string("offlinePrimaryVertices"),
							genParticleCollection = cms.string("genParticles"),
							trackCollection = cms.string("generalTracks"),
							absIsoDiscriminator = cms.string("hpsPFTauDiscriminationByRawCombinedIsolationDBSumPtCorr3Hits"),
							looseCombinedIsoDiscriminator = cms.string("hpsPFTauDiscriminationByLooseCombinedIsolationDBSumPtCorr3Hits"),
							mediumCombinedIsoDiscriminator = cms.string("hpsPFTauDiscriminationByMediumCombinedIsolationDBSumPtCorr3Hits"),
							tightCombinedIsoDiscriminator = cms.string("hpsPFTauDiscriminationByTightCombinedIsolationDBSumPtCorr3Hits"),
							looseMvaIsoDiscriminator = cms.string("hpsPFTauDiscriminationByLooseIsolationMVArun2v1DBoldDMwLT"),
							mediumMvaIsoDiscriminator = cms.string("hpsPFTauDiscriminationByMediumIsolationMVArun2v1DBoldDMwLT"),
							tightMvaIsoDiscriminator = cms.string("hpsPFTauDiscriminationByTightIsolationMVArun2v1DBoldDMwLT"),
							looseMuonRejectionDiscriminator = cms.string("hpsPFTauDiscriminationByLooseMuonRejection3"),
							tightMuonRejectionDiscriminator = cms.string("hpsPFTauDiscriminationByTightMuonRejection3"),
							looseElectronRejectionDiscriminator = cms.string("hpsPFTauDiscriminationByMVA6VLooseElectronRejection"),
							tightElectronRejectionDiscriminator = cms.string("hpsPFTauDiscriminationByMVA6VTightElectronRejection"),
							
)
