import FWCore.ParameterSet.Config as cms

treemaker = cms.EDAnalyzer("TreeMaker",
							isMC = cms.bool(False),
							tauPtMin = cms.double(50),
							piPtMin = cms.double(30),
							tauEtaMax = cms.double(2.1),
							tauDzMax = cms.double(0.2),
							null = cms.double(-5),
							Triggers = cms.vstring("HLT_LooseIsoPFTau50_Trk30_eta2p1_MET90_v1",
							                        "HLT_LooseIsoPFTau50_Trk30_eta2p1_MET90_v2",
							                        "HLT_LooseIsoPFTau50_Trk30_eta2p1_MET90_v3",
							                        "HLT_LooseIsoPFTau50_Trk30_eta2p1_MET90_v4",
							                        "HLT_LooseIsoPFTau50_Trk30_eta2p1_MET90_v5",
							                        "HLT_LooseIsoPFTau50_Trk30_eta2p1_MET90_v6",
							                        "HLT_LooseIsoPFTau50_Trk30_eta2p1_MET90_v7",
							                        "HLT_LooseIsoPFTau50_Trk30_eta2p1_MET90_v8",
							                        "HLT_LooseIsoPFTau50_Trk30_eta2p1_MET90_v9"
							                        ),
							tauCollection = cms.string("hpsPFTauProducer"),
							muonCollection = cms.string("muons"),
							electronCollection = cms.string("gedGsfElectrons"),
							jetCollection = cms.string("ak4PFJets"),
							metCollection = cms.string("pfMet"),
							vertexCollection = cms.string("offlinePrimaryVertices"),
							genParticleCollection = cms.string("genParticles"),
							trackCollection = cms.string("generalTracks"),
							absIsoDiscriminator = cms.string("hpsPFTauDiscriminationByRawCombinedIsolationDBSumPtCorr3Hits"),
							looseCombinedIsoDiscriminator = cms.string("hpsPFTauDiscriminationByLooseCombinedIsolationDBSumPtCorr3Hits"),
							mediumCombinedIsoDiscriminator = cms.string("hpsPFTauDiscriminationByMediumCombinedIsolationDBSumPtCorr3Hits"),
							tightCombinedIsoDiscriminator = cms.string("hpsPFTauDiscriminationByTightCombinedIsolationDBSumPtCorr3Hits"),
							looseMvaIsoDiscriminator = cms.string("hpsPFTauDiscriminationByLooseIsolationMVArun2v1DBoldDMwLT"),
							mediumMvaIsoDiscriminator = cms.string("hpsPFTauDiscriminationByMediumIsolationMVArun2v1DBoldDMwLT"),
							tightMvaIsoDiscriminator = cms.string("hpsPFTauDiscriminationByTightIsolationMVArun2v1DBoldDMwLT"),
							looseMuonRejectionDiscriminator = cms.string("hpsPFTauDiscriminationByLooseMuonRejection3"),
							tightMuonRejectionDiscriminator = cms.string("hpsPFTauDiscriminationByTightMuonRejection3"),
							looseElectronRejectionDiscriminator = cms.string("hpsPFTauDiscriminationByMVA6VLooseElectronRejection"),
							tightElectronRejectionDiscriminator = cms.string("hpsPFTauDiscriminationByMVA6VTightElectronRejection"),
							
)
